### ISSUE TITLE
Proper credit for immutable-css

### ISSUE THREAD

**Issue by jxnblk** [chibicode/react-functional-css-protips#3]
Hey, great article!

Just noticed a small typo:
[immutable-css](https://github.com/johnotander/immutable-css) was created by John Otander, not Jon Gold. I started to make a PR, but wasn't sure if a link to immutable-css made sense in the *Articles* section. Would you consider an appendix with miscellaneous links?

**Comment by chibicode** [comment]
Oh my god @jxnblk I'm sorry (and very sorry to John and Jon), I totally misunderstood. I'll add an appendix immediately.

**Comment by chibicode** [comment]
@jxnblk added! https://github.com/chibicode/react-functional-css-protips#appendix
