### ISSUE TITLE
Atomic CSS Modules

### ISSUE THREAD

**Issue by MicheleBertoli** [chibicode/react-functional-css-protips#6]
hey @chibicode, great article. 
thanks for writing and sharing it.

we've been doing some experiments with Atomic CSS and CSS Modules recently.
you may like this post: 
https://medium.com/yplan-eng/atomic-css-modules-cb44d5993b27

have a nice day!

**Comment by chibicode** [comment]
Thanks @MicheleBertoli! I actually have "Recommended" that article on Medium in the past. I just linked it at the bottom of the page. Looking forward to seeing the library open being sourced!
