### ISSUE TITLE
Aphrodite and Glamor worth mentioning

### ISSUE THREAD

**Issue by KyleAMathews** [chibicode/react-functional-css-protips#9]
Don't have the same problems as Radium.

Might be worth mentioning.

**Comment by chibicode** [comment]
@KyleAMathews thanks! [Aphrodite is already mentioned](https://github.com/chibicode/react-functional-css-protips/tree/abd4007671b7db12f427db527047389d902fd921#side-note-alternatives). I'll add Glamor!
